name: cxhero
description: Lightweight event tracking for Flutter with per-session and optional user-id scoping, persisted as JSON on disk, plus configurable micro-surveys.
version: 0.1.0
homepage: https://github.com/indigothm/cxhero-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.2.0
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
